name: Backport

on:
  workflow_dispatch:
    inputs:
      target:
        required: true
        default: "the-target"
      commit:
        required: true
        default: ""

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
    - uses: tomleb/gha-tests/backport@main
      # - run: |
      #     BRANCH="test-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
      #     gh repo clone ${{ github.repository }}
      #     cd gha-tests
      #     git checkout $TARGET
      #     git --global config user.email "tomleb@tomlebreux.com"
      #     git --global config user.name "Tom Lebreux"
      #     git checkout -b "$BRANCH"
      #     git cherry-pick $COMMIT
      #     git push -u origin "$BRANCH"
      #     gh pr create \
      #         --title "test" \
      #         --repo ${{ github.repository }} \
      #         --head "${{ github.repository_owner }}:$BRANCH" \
      #         --base "$TARGET"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     COMMIT: ${{ github.event.inputs.commit }}
      #     TARGET: ${{ github.event.inputs.target }}
